FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Installez les dépendances, y compris Tailwind
RUN npm install && \
    npm install -D tailwindcss postcss autoprefixer && \
    npx tailwindcss init -p

COPY . .

EXPOSE 3000

CMD ["npm", "start"]