security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email
        instructor_provider:
            entity:
                class: App\Entity\Instructor
                property: mail
        student_provider:
            entity:
                class: App\Entity\Student
                property: mail
        app_user_provider:
            chain:
                providers: ['admin_provider', 'instructor_provider', 'student_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login_check
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login
                invalidate_session: true
                delete_cookies:
                    PHPSESSID: { path: null, domain: null, secure: true, samesite: 'strict' }
                    jwt_token: { path: null, domain: null, secure: true, samesite: 'strict' }

    access_control:
        - { path: ^/api/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/mydojang, roles: ROLE_INSTRUCTOR }
        - { path: ^/profile, roles: ROLE_STUDENT }
        - { path: ^/api$, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/contexts, roles: PUBLIC_ACCESS }
        - { path: ^/api/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10