name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_sqlite, intl
          coverage: xdebug

      - name: Copy .env.test
        run: php -r "file_exists('.env.test') || copy('.env.test.dist', '.env.test');"
        
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Ajout des étapes pour EasyAdmin et API Platform
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: |
          npm run build
          php bin/console assets:install public
          php bin/console cache:clear --env=test

      - name: Generate JWT Keys
        run: |
          mkdir -p config/jwt
          openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -pass pass:${{ secrets.JWT_PASSPHRASE }}
          openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout -passin pass:${{ secrets.JWT_PASSPHRASE }}

      - name: Setup Database
        env:
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"
          APP_ENV: test
          JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
        run: |
          php bin/console doctrine:schema:create --env=test
          php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Execute Tests
        env:
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"
          APP_ENV: test
          JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
        run: php bin/phpunit --debug



  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Run Tests
        working-directory: ./frontend
        run: npm run vitest

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     file: ./frontend/coverage/coverage-final.json
      #     fail_ci_if_error: true

